baseURL: "https://jeffreymoro.com/"
languageCode: "en-us"
title: "Jeffrey Moro"
theme: cupper-hugo-theme

pluralizelisttitles: "false"

params:
  blogPaginate: 10
  description: "media / nature"
  twitter:
    site: "jeffreymoro"
    creator: "jeffreymoro"

paginate: 10

permalinks:
  blog: /blog/:year-:month-:day-:filename
#  research:
#  teaching:

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: CV
      url: /files/moro_cv-2024-03-25.pdf
      weight: 2
    - name: Research
      url: /research/
      weight: 3
    # - name: Teaching
    #  url: /teaching/
    #  weight: 4
    - name: Blog
      url: /blog/
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
